### PR TITLE
chore(NODE-3618): create action to upload prebuilds

### PR DESCRIPTION
**Pull request by nbbeeken**
This repeats the logic in run-prebuild.sh but I don't know how I would test to confirm, I think we have to just try tagging.

### CODE REVIEW

**Comment by dariakp** [comment]
@nbbeeken If it fails, what's the worst that would happen and how would we go about fixing?

**Comment by nbbeeken** [comment]
It won't upload the prebuilds, I think I would make a pull request that changes this action to trigger on a pull request. So we'd be able to run again and debug from there.

**Comment by nbbeeken** [comment]
@dariakp investigation went well and I can confirm it will upload correctly for all 3 OSes when we make the next v2 tag.

**Review by dariakp — APPROVED** [review]
@nbbeeken Thank you!

**Pull request merged**
